services:
  app:
    image: robiningelbrecht/strava-statistics:latest
    container_name: statistics-for-strava
    restart: unless-stopped
    volumes:
      - '/home/${USER}/server/statistics-for-strava/config:/var/www/config/app'
      - '/home/${USER}/server/statistics-for-strava/build:/var/www/build'
      - '/home/${USER}/server/statistics-for-strava/storage/database:/var/www/storage/database'
      - '/home/${USER}/server/statistics-for-strava/storage/files:/var/www/storage/files'
    env_file: ./.env
    ports:
      - 8080:8080