---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

title: Homeserver

theme: dark

color: slate

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
